version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql

  server:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: server
    ports:
      - '3000:3000'
    depends_on:
      - mysql
    environment:
      DATABASE_URL: mysql://jkici60lj45ssgs8rkmr:pscale_pw_iG2LjcCBBgQuVi57gqJpbxJCArbGRWlTIoOePBorp4X@aws.connect.psdb.cloud/computer-serve?sslaccept=strict
      SERVER_PORT: 3000

volumes:
  mysql-data:
